# This file was auto-generated by lib/generators/tasks/generate.rb

module Slack
  module Endpoint
    module Auth
      #
      # This method checks authentication and tells you who you are.
      #
      # @see https://api.slack.com/methods/auth.test
      # @see https://github.com/aki017/slack-api-docs/blob/master/methods/auth.test.md
      # @see https://github.com/aki017/slack-api-docs/blob/master/methods/auth.test.json
      def auth_test(options={})
        options[:attachments] = options[:attachments].to_json if Hash === options[:attachments]
        post("auth.test", options)
      end

    end
  end
end
