# This file was auto-generated by lib/generators/tasks/generate.rb

module Slack
  module Endpoint
    module Bots
      #
      # This method returns information about a bot user.
      #
      # @option options [Object] :bot
      #   Bot user to get info on
      # @see https://api.slack.com/methods/bots.info
      # @see https://github.com/aki017/slack-api-docs/blob/master/methods/bots.info.md
      # @see https://github.com/aki017/slack-api-docs/blob/master/methods/bots.info.json
      def bots_info(options={})
        post("bots.info", options)
      end

    end
  end
end
