# This file was auto-generated by lib/generators/tasks/generate.rb

module Slack
  module Endpoint
    module Emoji
      #
      # This method lists the custom emoji for a team.
      #
      # @see https://api.slack.com/methods/emoji.list
      # @see https://github.com/aki017/slack-api-docs/blob/master/methods/emoji.list.md
      # @see https://github.com/aki017/slack-api-docs/blob/master/methods/emoji.list.json
      def emoji_list(options={})
        post("emoji.list", options)
      end

    end
  end
end
