# This file was auto-generated by lib/generators/tasks/generate.rb

module Slack
  module Endpoint
    module Team
      #
      # Gets information for the current team
      #
      # @see https://api.slack.com/methods/team.info
      def team_info(options={})
        post("team.info", options)
      end

      #
      # This method is used to get the access logs for users on a team.
      #
      # @see https://api.slack.com/methods/team.accessLogs
      def team_accessLogs(options={})
        post("team.accessLogs", options)
      end

    end
  end
end
